### ISSUE TITLE
ChannelServer issues & Question about Cash Shop

### ISSUE THREAD

**Issue by nosutori** [retep998/Vana#4] opened 2015-10-11 14:53 UTC
I was just traveling to see what wasn't working and after 5 or 10 minutes or research i get disconnected and an error pops saying that ChannelServer has stopped working.

Also, I've got a question. Cash shop isn't implemented, right? Since i see no CashServer.exe anymore.
That's it, thanks.

**Comment by LazyBui** [comment] 2015-10-11 21:44
That means the ChannelServer has crashed. I need more information to discern what the cause is and how to fix it, because that definitely does not happen to me. Please review the bug report guidelines and include some more detail. https://github.com/VanaDev/Vana/wiki/Bug-reporting

Cash shop is not implemented on my branch. The main Vana branch has the cash shop.

**Comment by LazyBui** [comment] 2016-10-16 21:58
Closing. Please reopen with more detail if this still occurs.

**Closed as completed by LazyBui** 2016-10-16 21:58 UTC
